export const EMIT_TYPE = {
    SET_ADICT_SETTINGS: 'SET_ADICT_SETTINGS',
    SET_MACHINE_INFO: 'SET_MACHINE_INFO',
    SET_COLLECTOR_SETTINGS: 'SET_COLLECTOR_SETTINGS',
    SET_CREDENTIALS: 'SET_CREDENTIALS',
    SET_SSH_LOGIN: 'SET_SSH_LOGIN',
    SET_IPFIXPROBE_SETTINGS: 'PROBES_CONN_INFO',
    SET_MASTER_PASSWORD: 'SET_MASTER_PASSWORD',
    SET_PROBES_CONN_INFO: 'AUTO_DISCOVERY',
    IPFIXPROBE_INPUT_SETUP: 'IPFIXPROBE_INPUT_SETUP'
};
