export const STATE = {
    MASTER_PASSWORD_SETUP: 'MASTER_PASSWORD_SETUP',
    GLOBAL_SSH_INIT: 'GLOBAL_SSH_INIT',
    COLLECTOR_SETTINGS: 'COLLECTOR_SETTINGS',
    CUSTOM_COL_CREDENTIALS: 'CUSTOM_COL_CREDENTIALS',
    ADICT_SETTINGS: 'ADICT_SETTINGS',
    PROBES_CONN_INFO: 'PROBES_CONN_INFO',
    CUSTOM_PROBE_CREDENTIALS: 'CUSTOM_PROBE_CREDENTIALS',
    AUTO_DISCOVERY: 'AUTO_DISCOVERY',
    IPFIXPROBE_INPUT_SETUP: 'IPFIXPROBE_INPUT_SETUP',
    NEXT: 'NEXT'
};
